spring.application.name=discovery-service
server.port=8761

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.username=${EUREKA_USERNAME:eureka}
eureka.password=${EUREKA_PASSWORD:password}

management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=${OTLP_ENDPOINT:http://localhost:4318/v1/traces}
management.endpoint.web.exposure.include=prometheus
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]