spring.datasource.url=jdbc:mysql://mysql-inventory:3306/inventorydb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:password}@discovery-server:8761/eureka/
management.otlp.tracing.endpoint=${OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}